# Scenario 1:
# 3 * rgnb
# 1 * gnb
# 2 * UE

services:
  free5gc-upf:
    container_name: upf
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/upfcfg.yaml:/free5gc-5g-relays/config/upfcfg.yaml
      - ./config/upf-iptables.sh:/free5gc-5g-relays/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - upf.free5gc.org

  db:
    container_name: mongodb
    image: mongo
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      privnet:
        aliases:
          - db

  free5gc-nrf:
    container_name: nrf
    build:
      context: ./nf_nrf
      args:
        DEBUG_TOOLS: "false"
    command: ./nrf -c ./config/nrfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nrfcfg.yaml:/free5gc-5g-relays/config/nrfcfg.yaml
      - ./cert:/free5gc-5g-relays/cert
    environment:
      DB_URI: mongodb://db/free5gc-5g-relays
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nrf.free5gc.org
    depends_on:
      - db

  free5gc-amf:
    container_name: amf
    build:
      context: ./nf_amf
      args:
        DEBUG_TOOLS: "false"
    command: ./amf -c ./config/amfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/amfcfg.yaml:/free5gc-5g-relays/config/amfcfg.yaml
      - ./cert:/free5gc-5g-relays/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.200.16
        aliases:
          - amf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    container_name: ausf
    build:
      context: ./nf_ausf
      args:
        DEBUG_TOOLS: "false"
    command: ./ausf -c ./config/ausfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/ausfcfg.yaml:/free5gc-5g-relays/config/ausfcfg.yaml
      - ./cert:/free5gc-5g-relays/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - ausf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    container_name: nssf
    build:
      context: ./nf_nssf
      args:
        DEBUG_TOOLS: "false"
    command: ./nssf -c ./config/nssfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nssfcfg.yaml:/free5gc-5g-relays/config/nssfcfg.yaml
      - ./cert:/free5gc-5g-relays/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nssf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    container_name: pcf
    build:
      context: ./nf_pcf
      args:
        DEBUG_TOOLS: "false"
    command: ./pcf -c ./config/pcfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/pcfcfg.yaml:/free5gc-5g-relays/config/pcfcfg.yaml
      - ./cert:/free5gc-5g-relays/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - pcf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    container_name: smf
    build:
      context: ./nf_smf
      args:
        DEBUG_TOOLS: "false"
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./config/smfcfg.yaml:/free5gc-5g-relays/config/smfcfg.yaml
      - ./config/uerouting.yaml:/free5gc-5g-relays/config/uerouting.yaml
      - ./cert:/free5gc-5g-relays/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - smf.free5gc.org
    depends_on:
      - free5gc-nrf
      - free5gc-upf

  free5gc-udm:
    container_name: udm
    build:
      context: ./nf_udm
      args:
        DEBUG_TOOLS: "false"
    command: ./udm -c ./config/udmcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udmcfg.yaml:/free5gc-5g-relays/config/udmcfg.yaml
      - ./cert:/free5gc-5g-relays/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - udm.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-udr:
    container_name: udr
    build:
      context: ./nf_udr
      args:
        DEBUG_TOOLS: "false"
    command: ./udr -c ./config/udrcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udrcfg.yaml:/free5gc-5g-relays/config/udrcfg.yaml
      - ./cert:/free5gc-5g-relays/cert
    environment:
      DB_URI: mongodb://db/free5gc-5g-relays
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - udr.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-chf:
    container_name: chf
    build:
      context: ./nf_chf
      args:
        DEBUG_TOOLS: "false"
    command: ./chf -c ./config/chfcfg.yaml
    expose:
      - "8000"
      - "2122"
    volumes:
      - ./config/chfcfg.yaml:/free5gc-5g-relays/config/chfcfg.yaml
      - ./cert:/free5gc-5g-relays/cert
    environment:
      DB_URI: mongodb://db/free5gc-5g-relays
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - chf.free5gc.org
    depends_on:
      - db
      - free5gc-nrf
      - free5gc-webui

  free5gc-webui:
    container_name: webui
    build:
      context: ./webui
      args:
        DEBUG_TOOLS: "false"
    command: ./webui -c ./config/webuicfg.yaml
    expose:
      - "2121"
    volumes:
      - ./config/webuicfg.yaml:/free5gc-5g-relays/config/webuicfg.yaml
    environment:
      - GIN_MODE=release
    networks:
      privnet:
        aliases:
          - webui
    ports:
      - "5000:5000"
    depends_on:
      - db
      - free5gc-nrf

  rgnb1:
    container_name: rgnb1
    build:
      context: ./../.
      dockerfile: ./free5gc-compose-5G-relays/rgnb/Dockerfile
    command: ./nr-rgnb -c ./config/scenario-5/rgnb1-cfg.yaml
    volumes:
      - ./config/scenario-5/rgnb1-cfg.yaml:/ueransim-5g-relays/config/scenario-5/rgnb1-cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - rgnb1.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-upf
      - rgnb2
      - rgnb3
      - gnb1

  rgnb2:
    container_name: rgnb2
    build:
      context: ./../.
      dockerfile: ./free5gc-compose-5G-relays/rgnb/Dockerfile
    command: ./nr-rgnb -c ./config/scenario-5/rgnb2-cfg.yaml
    volumes:
      - ./config/scenario-5/rgnb2-cfg.yaml:/ueransim-5g-relays/config/scenario-5/rgnb2-cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - rgnb2.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-upf
      - gnb1
      - rgnb3

  rgnb3:
    container_name: rgnb3
    build:
      context: ./../.
      dockerfile: ./free5gc-compose-5G-relays/rgnb/Dockerfile
    command: ./nr-rgnb -c ./config/scenario-5/rgnb3-cfg.yaml
    volumes:
      - ./config/scenario-5/rgnb3-cfg.yaml:/ueransim-5g-relays/config/scenario-5/rgnb3-cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - rgnb3.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-upf
      - gnb1

  gnb1:
    container_name: gnb1
    build:
      context: ./ueransim
    command: ./nr-gnb -c ./config/scenario-5/gnb1cfg.yaml
    volumes:
      - ./config/scenario-5/gnb1cfg.yaml:/ueransim/config/scenario-5/gnb1cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - gnb1.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-upf

  ue1:
    container_name: ue1
    build:
      context: ./ueransim
    command: ./nr-ue -c ./config/scenario-5/ue1-cfg.yaml
    volumes:
      - ./config/scenario-5/ue1-cfg.yaml:/ueransim/config/scenario-5/ue1-cfg.yaml
      - ./config/ping-experiment-2.sh:/ueransim/config/ping-experiment-2.sh
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue1.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-upf
      - rgnb1
      - rgnb2
      - rgnb3
      - gnb1

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc
  

volumes:
  dbdata:
